FROM node:20-slim

# Set the working directory
WORKDIR /app/frontend 

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install dependencies
RUN npm install --legacy-peer-dep

# Copy the rest of the application code
COPY frontend/ .

# Build the application
RUN npm run build

# Expose the port the app runs on 
EXPOSE 3000

CMD [ "npm", "start" ]