services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    working_dir: /app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - backend/.env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    working_dir: /app/frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app/frontend/node_modules
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    
  # Remove the comment to enable pgAdmin to manage the PostgreSQL database
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8080:80"

volumes:
  db_data: