"""Update Blog model

Revision ID: 9a7d452d1b0b
Revises: ac8960d4547d
Create Date: 2025-06-01 10:13:53.632796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7d452d1b0b'
down_revision: Union[str, None] = 'ac8960d4547d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('blogs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'updated_at')
    op.drop_column('blogs', 'created_at')
    # ### end Alembic commands ###
